### PR TITLE
Add navigating between page feature on h and l key

### PR DESCRIPTION
**Pull request by edykim**
I added l and h key events to handle navigation between pages. By pressing the h and l key, the user can move to the previous page or next page.

Related #2

### CODE REVIEW

**Review by channprj — APPROVED** [review]
Great idea! Thank you for your contribution! :tada:

**Comment by edykim** [comment]
@channprj I'm sorry to bother you. My PRs are invalid from the hacktoberfest due to `hacktoberfest` topic removal from your repository. Could you add `hacktoberfest-accepted` label on my PRs or add `hacktoberfest` topic back on the repository? :smile:

**Comment by channprj** [comment]
@edykim I thought the event had already ended. Sorry for your inconvenience. Thank you for noticing. ☺️

**Comment by edykim** [comment]
@channprj It seems like the counting has gone already even though the label added. I guess they are not updating the contribution after being ineligible. 😭

Screen Shot 2020-11-02 at 7 05 21 PM

**Comment by channprj** [comment]
> This year, we’re also extending the validation period from one week to 14 days. This will give maintainers more time to review pull requests before contributors earn their shirts.

I added `hacktoberfest` and `hacktobefest-accepted`, but I think it may take some time before it is actually applied. It would be a good idea to send an inquiry email to the [hacktoberfest](https://hacktoberfest.digitalocean.com/).

**Comment by channprj** [comment]
@edykim If your PR is still ineligible, I will contact hacktoberfest.

**Pull request merged**
